### ISSUE TITLE
Too much code repeating

### ISSUE THREAD

**Issue by RomanHood** [TaliSofiMato/scoreboard#10]
There are four scoring functions which all do basically the same thing. They increment the score then re-render. They only differ on how much they increment it by and which team's score they increment.

Refactor those four functions down to one which does the same thing _dynamically_. In all four of those functions two things are _hard coded_, the number and the team. Functions can take arguments which act as variables within the function. 

After you have one scoring function which handles all the scoring change the html call site to call that function, passing in the dynamic parameters.

**Comment by TaliSofiMato** [comment]
Done dynamically! swishh! 😉
