### ISSUE TITLE
To many different calls to re-render

### ISSUE THREAD

**Issue by RomanHood** [TaliSofiMato/scoreboard#11]
This project has a lot of event listeners that change state then re-render. They re-render _something_, usually something different. It is good to have many different re-rending functions, one for each component. That keeps your code very clean, specific, and organized. 

But the app is _always_ a function of its state; apps _always_ simply render "the current state of the app."

Change all the call sites of `render{Something}()` to simply `render()` (the same function that runs `onload`). This should _not affect_ any function definitions. 

When state changes re-rendering the entire app is not any different than targeting one small component to re-render. In fact, the former is simpler, and make debugging easier because every single re-render is now doing the exact same thing. Now it is even _more clear_ that event listeners simply change state then `rerender()`

**Comment by TaliSofiMato** [comment]
buggies!
My initial  pass caused problems, I will further investigate. 😁

**Comment by RomanHood** [comment]
After investigating, it turns out that the inconsistent behavior that this approach caused with the game clock was due to the gameClock timeout function not yet being updated to the new event->state change-> pattern. In a separate PR I will update that function to the new pattern, and implement this `rerender()` work together.

**Comment by TaliSofiMato** [comment]
Done! :)
