### ISSUE TITLE
Make button text dynamice

### ISSUE THREAD

**Issue by RomanHood** [TaliSofiMato/scoreboard#12]
We need to remove the hard coded values from the html buttons and set them in a renderer.

Set the textContent of the buttons by referencing the team name in state and producing a concatenated string (as you are doing with timeouts).

**Comment by RomanHood** [comment]
@TaliSofiMato can this be closed?

**Comment by RomanHood** [comment]
@TaliSofiMato .....................

**Comment by TaliSofiMato** [comment]
Done! 💯
