### ISSUE TITLE
All scoreboard elements and their default values (scores, team names) are visible when the app loads

### ISSUE THREAD

**Issue by RomanHood** [TaliSofiMato/scoreboard#15]
The expected behavior is not occuring when the screen is wider than a certain amount (about 1350 pixels apparently)

[
<img width="1792" alt="Screen Shot 2021-11-14 at 2 16 52 PM" src="https://user-images.githubusercontent.com/5008733/141695245-e5425fee-b998-4d93-999b-1de1627fec0d.png">
](url)

**Comment by TaliSofiMato** [comment]
Done! 😃
