### ISSUE TITLE
Lint the code

### ISSUE THREAD

**Issue by RomanHood** [TaliSofiMato/scoreboard#18]
Every project should use a linter. A linter is a tool to read through all your code and fix the annoying little syntax problems (missing semicolons, bad intenting, etc).

Every language has a package manager(s). Package managers go out to the internet and download libraries for that language onto your machine for you to use. For javascript/nodejs the default package manager is npm, which should already be installed on your machine.

For javascript code a popular linter is eslint. Eslint itself is a javascript library. First you have to install it on your machine, then run it inside your project folder.

- [x] Install eslint on your machine with `npm install -g eslint`
- [x] Initialize eslint inside your project with `eslint --init`. A menu will ask you a series of questions. Here is how I recommend you answer:
<img width="1245" alt="Screen Shot 2021-11-20 at 3 55 00 PM" src="https://user-images.githubusercontent.com/5008733/142740628-74c46119-e5c2-4ba3-b352-daf378763485.png">
That will create some new files inside your folder that will need to be committed.

- [x] Run eslint inside your project with `eslint <filename>`... I recommend you actually run `eslint .` which will run it for all files. 

That command will produce a lot of output. The output is a list of all the errors it found. Most of them you can fix by re-running the same command with the `--fix` option (`eslint --fix .`). After you run that there will be changes to all or most of your files. Those will have to be committed.
After eslint has automatically fixed many of the errors you will have to manually fix the rest. The output of `eslint --fix .` will tell you the filename, the line number, and a description of every error it found. Once you've made all the necessary fixes, commit all those files.

- [x] Run `eslint .` one final time to make sure the output shows nothing to fix.

**Comment by TaliSofiMato** [comment]
Done :) 💯
