### ISSUE TITLE
Out-of-date code

### ISSUE THREAD

**Issue by RomanHood** [TaliSofiMato/scoreboard#4]
You implemented your four scoring functions (`PHX2`, `LAC3`, etc.) before implementing the new pattern of state-changes, i.e. Event -> Change State -> Re-render

Refactor (rewrite) those four scoring functions to update the state and re-render, instead of [setting the text content to a new value directly](https://github.com/TaliSofiMato/scoreboard/blob/fc9373bebdc61754702e1489b90d3bd705375c8e/eventListeners.js#L5). An example of a function already using the new pattern is [`prepClock`](https://github.com/TaliSofiMato/scoreboard/blob/fc9373bebdc61754702e1489b90d3bd705375c8e/eventListeners.js#L106)

**Comment by TaliSofiMato** [comment]
Done!!! Thank you!
