### ISSUE TITLE
Out-of-date code

### ISSUE THREAD

**Issue by RomanHood** [TaliSofiMato/scoreboard#6]
The [`startShotClock`](https://github.com/TaliSofiMato/scoreboard/issues/new) function was written before you transitioned to your new state-update pattern.

Refactor that function to simply change state and re-render. Notice that that function is also changing the styling (the color) of the text. That will have to be removed and shoved into the `renderShotClock` function. Inside that function, use an `if() {}` statement which checks `state` to determine what color to set it to.

**Comment by TaliSofiMato** [comment]
Done!
