### ISSUE TITLE
team-specific code

### ISSUE THREAD

**Issue by RomanHood** [TaliSofiMato/scoreboard#7]
This scoreboard application should be able to be used with any two teams. This means more than just keeping track of team names in state, because much of the code references the team names specifically. You have functions named `LAC2` and css classes named `timeoutphx`, etc...

This should never be. Our function names and other code-objects should always be as generic and flexible as possible.

Refactor all files that reference phx and lac to have generic and re-usable naming conventions. Instead of keeping track of phx and lac, we should be keeping track of "homeTeam" and "visitingTeam".

**Comment by TaliSofiMato** [comment]
Done!
