### ISSUE TITLE
Layout breaks when resizing

### ISSUE THREAD

**Issue by RomanHood** [TaliSofiMato/scoreboard#8]
Problem statement:
The layout of the scoreboard is unreliable and inconsistent when resizing the browser window.

![cssbug](https://user-images.githubusercontent.com/5008733/141519310-99c8cd08-25b9-40c2-b3e6-31f73a33c69e.gif)

Steps to reproduce:

1. Load the app in your browser
2. Horizontally resize your browser window left and right, shrinking and expanding the app

Acceptance Criteria:

- [x] All scoreboard elements and their default values (scores, team names) are visible when the app loads
- [x] The scoreboard has a minimum width of 600px and if the window ever shrinks thinner than that the scoreboard stays unchanged and the right-side is cutoff.
- [x] When the browser width exceeds the minimum width of the scoreboard the scoreboard stretches to fill 100% of the screen.

**Comment by TaliSofiMato** [comment]
Done!
