### ISSUE TITLE
`prepClock` only goes to second quarter

### ISSUE THREAD

**Issue by RomanHood** [TaliSofiMato/scoreboard#9]
We need our game to be able to advance to the 3rd and 4th quarters.

Currently, `prepClock` is hard-coding "2nd" as the next quarter.

Refactor `prepClock` to _increment_ the quarter based on what it currently is. For the full text (the letters after the number) to be correct, you'll have to implement some logic to map 1 to "1st" and 3 to "3rd" for example. See the `labels` map and how its being looked up in [this function](https://github.com/TaliSofiMato/scoreboard/blob/97770184a332ec1b4955562b1ec24747042626b4/renderers.js#L30) for an example of how to do this.

Further reading: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Working_with_Objects

**Comment by TaliSofiMato** [comment]
Done! 😄
